-- Weather MLOps Supabase schema
-- Project: jul26_bmlops_int_weather
--
-- This is the canonical database schema for the shared Supabase project.
-- Apply it in the Supabase SQL Editor or via:
--   psql "$SUPABASE_DB_URL" -f supabase/schema.sql

create extension if not exists "uuid-ossp";

-- Phase 1: WeatherAUS raw data loaded by scripts/load_to_supabase.py.
create table if not exists public.weather_observations (
    date date not null,
    location text not null,
    source_row_number integer,
    min_temp double precision,
    max_temp double precision,
    rainfall double precision,
    evaporation double precision,
    sunshine double precision,
    wind_gust_dir text,
    wind_gust_speed double precision,
    wind_dir_9am text,
    wind_dir_3pm text,
    wind_speed_9am double precision,
    wind_speed_3pm double precision,
    humidity_9am double precision,
    humidity_3pm double precision,
    pressure_9am double precision,
    pressure_3pm double precision,
    cloud_9am double precision,
    cloud_3pm double precision,
    temp_9am double precision,
    temp_3pm double precision,
    rain_today text,
    rain_tomorrow text,
    ingested_at timestamptz not null default now(),
    source text not null default 'weatherAUS',
    primary key (date, location)
);

create index if not exists idx_weather_observations_date_location
    on public.weather_observations (date, location);

create index if not exists idx_weather_observations_location
    on public.weather_observations (location);

-- Dataset metadata written by scripts/register_dataset_version.py.
create table if not exists public.dataset_versions (
    dataset_name text not null,
    path text not null,
    size_bytes bigint not null,
    md5 text not null,
    sha256 text not null,
    created_at timestamptz not null,
    version_kind text not null default 'raw',
    storage_uri text,
    git_commit text,
    preprocessing_version text,
    parent_sha256 text,
    source text not null default 'weatherAUS',
    created_by text not null default 'local',
    primary key (dataset_name, sha256)
);

-- Supabase Storage bucket used as the DVC S3-compatible remote.
insert into storage.buckets (id, name, public)
values ('weather-mlops-dvc', 'weather-mlops-dvc', false)
on conflict (id) do nothing;

-- Future model registry mirror. MLflow is intentionally deferred for now, so
-- mlflow_run_id is nullable until that stage is implemented.
create table if not exists public.model_versions (
    id bigserial primary key,
    mlflow_run_id text unique,
    mlflow_model_uri text,
    artifact_path text,
    dataset_sha256 text,
    name text not null,
    stage text not null default 'None',
    metrics jsonb,
    params jsonb,
    tags jsonb,
    registered_at timestamptz not null default now()
);

-- Future prediction log for the API and drift checks.
create table if not exists public.predictions (
    id uuid primary key default uuid_generate_v4(),
    prediction_ts timestamptz not null default now(),
    model_version_id bigint,
    features jsonb not null,
    predicted_value numeric,
    predicted_class text,
    probability double precision,
    request_id text,
    latency_ms integer
);

do $$
begin
    if not exists (
        select 1 from pg_constraint where conname = 'predictions_model_version_fk'
    ) then
        alter table public.predictions
            add constraint predictions_model_version_fk
            foreign key (model_version_id)
            references public.model_versions(id)
            on delete set null;
    end if;
end$$;

create index if not exists idx_predictions_ts
    on public.predictions (prediction_ts desc);

create index if not exists idx_predictions_model_version
    on public.predictions (model_version_id, prediction_ts desc);

create index if not exists idx_predictions_features_gin
    on public.predictions using gin (features);

-- Future drift reports generated by Evidently/Airflow.
create table if not exists public.drift_reports (
    id bigserial primary key,
    generated_at timestamptz not null default now(),
    scope text not null,
    reference_dataset text,
    current_dataset text,
    drift_detected boolean not null,
    metrics jsonb not null,
    report_html_path text,
    mlflow_run_id text
);

create index if not exists idx_drift_reports_generated_at
    on public.drift_reports (generated_at desc);

alter table public.weather_observations enable row level security;
alter table public.dataset_versions enable row level security;
alter table public.predictions enable row level security;
alter table public.model_versions enable row level security;
alter table public.drift_reports enable row level security;

-- The Python scripts use the server-side Supabase key, which bypasses RLS.
-- Authenticated policies are kept for later app/API development.
drop policy if exists auth_write_weather_obs on public.weather_observations;
create policy auth_write_weather_obs
    on public.weather_observations for all
    to authenticated
    using (true) with check (true);

drop policy if exists auth_write_dataset_versions on public.dataset_versions;
create policy auth_write_dataset_versions
    on public.dataset_versions for all
    to authenticated
    using (true) with check (true);

drop policy if exists auth_write_predictions on public.predictions;
create policy auth_write_predictions
    on public.predictions for all
    to authenticated
    using (true) with check (true);

drop policy if exists auth_write_model_ver on public.model_versions;
create policy auth_write_model_ver
    on public.model_versions for all
    to authenticated
    using (true) with check (true);

drop policy if exists auth_write_drift_rep on public.drift_reports;
create policy auth_write_drift_rep
    on public.drift_reports for all
    to authenticated
    using (true) with check (true);

-- Additive lineage columns for projects that already applied the Phase 1 schema.
alter table public.dataset_versions add column if not exists version_kind text not null default 'raw';
alter table public.dataset_versions add column if not exists storage_uri text;
alter table public.dataset_versions add column if not exists git_commit text;
alter table public.dataset_versions add column if not exists preprocessing_version text;
alter table public.dataset_versions add column if not exists parent_sha256 text;
alter table public.dataset_versions add column if not exists source text not null default 'weatherAUS';
alter table public.dataset_versions add column if not exists created_by text not null default 'local';

create index if not exists idx_dataset_versions_kind
    on public.dataset_versions (version_kind, created_at desc);

-- Immutable raw ingestion batches, separate from processed dataset snapshots.
create table if not exists public.ingestion_batches (
    id uuid primary key default uuid_generate_v4(),
    batch_date date not null,
    location_count integer,
    storage_uri text not null,
    sha256 text not null,
    source text not null default 'open-meteo',
    git_commit text,
    created_at timestamptz not null default now(),
    unique (batch_date, sha256)
);

create index if not exists idx_ingestion_batches_date
    on public.ingestion_batches (batch_date desc);

alter table public.ingestion_batches enable row level security;

drop policy if exists auth_write_ingestion_batches on public.ingestion_batches;
create policy auth_write_ingestion_batches
    on public.ingestion_batches for all
    to authenticated
    using (true) with check (true);

-- Private MLflow artifact bucket (Jonathan's tracking server). Dataset snapshots
-- reuse the existing DVC bucket weather-mlops-dvc with raw/ and processed/ prefixes.
insert into storage.buckets (id, name, public)
values ('weather-mlops-mlflow', 'weather-mlops-mlflow', false)
on conflict (id) do nothing;

-- Vault holds S3 keys and API basic auth (API_AUTH_USER / API_AUTH_PASSWORD).
-- Local .env only needs SUPABASE_URL + SUPABASE_KEY (service role).
do $$
begin
    create extension if not exists supabase_vault;
exception
    when others then
        raise notice 'supabase_vault extension not available: %', sqlerrm;
end$$;

create or replace function public.get_app_secret(secret_name text)
returns text
language plpgsql
security definer
set search_path = vault, pg_temp
as $$
declare
    value text;
begin
    if coalesce(auth.role(), current_user) not in ('service_role', 'postgres', 'supabase_admin') then
        raise exception 'not authorized to read vault secrets';
    end if;

    select decrypted_secret
      into value
      from vault.decrypted_secrets
     where name = secret_name
     limit 1;

    return value;
end;
$$;

revoke all on function public.get_app_secret(text) from public, anon, authenticated;
grant execute on function public.get_app_secret(text) to service_role, postgres;
