-- Weather MLOps Supabase schema
-- Project: jul26_bmlops_int_weather
--
-- This is the canonical database schema for the shared Supabase project.
-- Apply it in the Supabase SQL Editor or via:
--   psql "$SUPABASE_DB_URL" -f supabase/schema.sql

create extension if not exists "uuid-ossp";

-- Phase 1: WeatherAUS raw data loaded by scripts/load_to_supabase.py.
create table if not exists public.weather_observations (
    source_row_number integer primary key,
    date date,
    location text,
    min_temp double precision,
    max_temp double precision,
    rainfall double precision,
    evaporation double precision,
    sunshine double precision,
    wind_gust_dir text,
    wind_gust_speed double precision,
    wind_dir_9am text,
    wind_dir_3pm text,
    wind_speed_9am double precision,
    wind_speed_3pm double precision,
    humidity_9am double precision,
    humidity_3pm double precision,
    pressure_9am double precision,
    pressure_3pm double precision,
    cloud_9am double precision,
    cloud_3pm double precision,
    temp_9am double precision,
    temp_3pm double precision,
    rain_today text,
    rain_tomorrow text,
    ingested_at timestamptz not null default now(),
    source text not null default 'weatherAUS'
);

create index if not exists idx_weather_observations_date_location
    on public.weather_observations (date, location);

create index if not exists idx_weather_observations_location
    on public.weather_observations (location);

-- Dataset metadata written by scripts/load_to_supabase.py.
create table if not exists public.dataset_versions (
    dataset_name text not null,
    path text not null,
    size_bytes bigint not null,
    md5 text not null,
    sha256 text not null,
    created_at timestamptz not null,
    primary key (dataset_name, sha256)
);

-- Supabase Storage bucket used as the DVC S3-compatible remote.
insert into storage.buckets (id, name, public)
values ('weather-mlops-dvc', 'weather-mlops-dvc', false)
on conflict (id) do nothing;

-- Future model registry mirror. MLflow is intentionally deferred for now, so
-- mlflow_run_id is nullable until that stage is implemented.
create table if not exists public.model_versions (
    id bigserial primary key,
    mlflow_run_id text unique,
    mlflow_model_uri text,
    artifact_path text,
    dataset_sha256 text,
    name text not null,
    stage text not null default 'None',
    metrics jsonb,
    params jsonb,
    tags jsonb,
    registered_at timestamptz not null default now()
);

-- Future prediction log for the API and drift checks.
create table if not exists public.predictions (
    id uuid primary key default uuid_generate_v4(),
    prediction_ts timestamptz not null default now(),
    model_version_id bigint,
    features jsonb not null,
    predicted_value numeric,
    predicted_class text,
    probability double precision,
    request_id text,
    latency_ms integer
);

do $$
begin
    if not exists (
        select 1 from pg_constraint where conname = 'predictions_model_version_fk'
    ) then
        alter table public.predictions
            add constraint predictions_model_version_fk
            foreign key (model_version_id)
            references public.model_versions(id)
            on delete set null;
    end if;
end$$;

create index if not exists idx_predictions_ts
    on public.predictions (prediction_ts desc);

create index if not exists idx_predictions_model_version
    on public.predictions (model_version_id, prediction_ts desc);

create index if not exists idx_predictions_features_gin
    on public.predictions using gin (features);

-- Future drift reports generated by Evidently/Airflow.
create table if not exists public.drift_reports (
    id bigserial primary key,
    generated_at timestamptz not null default now(),
    scope text not null,
    reference_dataset text,
    current_dataset text,
    drift_detected boolean not null,
    metrics jsonb not null,
    report_html_path text,
    mlflow_run_id text
);

create index if not exists idx_drift_reports_generated_at
    on public.drift_reports (generated_at desc);

alter table public.weather_observations enable row level security;
alter table public.dataset_versions enable row level security;
alter table public.predictions enable row level security;
alter table public.model_versions enable row level security;
alter table public.drift_reports enable row level security;

-- The Python scripts use the server-side Supabase key, which bypasses RLS.
-- Authenticated policies are kept for later app/API development.
drop policy if exists auth_write_weather_obs on public.weather_observations;
create policy auth_write_weather_obs
    on public.weather_observations for all
    to authenticated
    using (true) with check (true);

drop policy if exists auth_write_dataset_versions on public.dataset_versions;
create policy auth_write_dataset_versions
    on public.dataset_versions for all
    to authenticated
    using (true) with check (true);

drop policy if exists auth_write_predictions on public.predictions;
create policy auth_write_predictions
    on public.predictions for all
    to authenticated
    using (true) with check (true);

drop policy if exists auth_write_model_ver on public.model_versions;
create policy auth_write_model_ver
    on public.model_versions for all
    to authenticated
    using (true) with check (true);

drop policy if exists auth_write_drift_rep on public.drift_reports;
create policy auth_write_drift_rep
    on public.drift_reports for all
    to authenticated
    using (true) with check (true);
